SKYPE_API = "com.Skype.API"
SKYPE_API_PATH = "/com/Skype"
SKYPE_CLIENT = "com.Skype.API.Client"
SKYPE_CLIENT_PATH = "/com/Skype/Client"
SKYPE_PROTOCOL = "7"
DBUS = "org.freedesktop.DBus"
DBUS_PATH = "/org/freedesktop/DBus"

SKYPE_DBUS_APP_NAME = "Skype_Dbus"

SKYPE_USER_STATUS_UNKNOWN = 0
SKYPE_USER_STATUS_ONLINE = 1
SKYPE_USER_STATUS_OFFLINE = 2
SKYPE_USER_STATUS_SKYPEME = 3
SKYPE_USER_STATUS_AWAY = 4
SKYPE_USER_STATUS_NA = 5
SKYPE_USER_STATUS_DND = 6
SKYPE_USER_STATUS_INVISIBLE = 7
SKYPE_USER_STATUS_LOGGEDOUT = 8